In [ ]:
#import the libraries 

import pandas as pd
import numpy as np

In [ ]:
#load the training dataset

df=pd.read_csv('sample_data/mnist_train_small.csv')

In [ ]:
#split df into feature set 'train_X' and label 'train_y'

train_y,train_X=np.hsplit(df,[1])
print(train_y.head())
print(train_X.head())

   6
0  5
1  7
2  9
3  5
4  2
   0  0.1  0.2  0.3  0.4  0.5  ...  0.585  0.586  0.587  0.588  0.589  0.590
0  0    0    0    0    0    0  ...      0      0      0      0      0      0
1  0    0    0    0    0    0  ...      0      0      0      0      0      0
2  0    0    0    0    0    0  ...      0      0      0      0      0      0
3  0    0    0    0    0    0  ...      0      0      0      0      0      0
4  0    0    0    0    0    0  ...      0      0      0      0      0      0

[5 rows x 784 columns]


In [ ]:
#normalize the feature set 'train_X' to get 'train_x'

train_x=train_X.copy()

#get the maximum datapoint in the entire feature set 'train_x'
maximum=train_x.max().max()  
print(maximum)

#divide the entire feature set 'train_x' with 'maximum'
train_x=train_x.div(maximum) 
train_x=train_x.astype('float64')
print (train_x.sample(5))

255
         0  0.1  0.2  0.3  0.4  0.5  ...  0.585  0.586  0.587  0.588  0.589  0.590
2701   0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
1984   0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
7412   0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
414    0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
16108  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0

[5 rows x 784 columns]


In [ ]:
#Add the bias column to the feature set 'train_x'

train_x=pd.concat([pd.Series(1.0,index=train_x.index,name='00'),train_x],axis=1)
print(train_x.head())

#'train_x_row' = number of rows in the feature set 'train_x'
train_x_row=train_x.shape[0]
print(train_x_row)

#'train_x_col' = number of columns in the feature set 'train_x'
train_x_col=train_x.shape[1]
print(train_x_col)

    00    0  0.1  0.2  0.3  0.4  ...  0.585  0.586  0.587  0.588  0.589  0.590
0  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
1  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
2  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
3  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
4  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0

[5 rows x 785 columns]
19999
785


In [ ]:
#check out how many unique classes are present in 'train_y'

train_y=train_y.iloc[:,0]
print(train_y.unique())

#'u' is an array containing all the unique class values 
u=train_y.unique()
clas=len(u)
print(clas)

[5 7 9 2 0 6 8 3 4 1]
10


In [ ]:
#convert feature and label dataframes to numpy array

train_x=train_x.to_numpy()
train_y=train_y.to_numpy()

In [ ]:
#enable one hot classification

one_hot_label=np.empty([train_x_row,clas])
for i in range(clas):
    for j in range(train_x_row):
        if(train_y[j]==u[i]):
            one_hot_label[j,i]=1
        else:
            one_hot_label[j,i]=0
print(one_hot_label[:10]) 

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#define the class logistic_regression

class log_reg:

  @staticmethod

  #define the hypothesis to calculate the expression (theta0*x0 + theta1*x1 + theta2*x2 + .....)

  def hypothesis(train_x,theta):
    hypothesis_output=np.dot(train_x,theta)
    return hypothesis_output

  #define the sigmoid function

  def sigmoid(pred):
    return 1/(1+np.exp(-pred))
    
   #define the derivative of sigmoid function

  def sigmoid_grad(sigmoid_output):
    return sigmoid_output*(1-sigmoid_output)

  #calculate the error

  def error(sigmoid_der,one_hot_label_column):
    err=np.zeros(train_x_row,dtype='float64')
    for i in range(train_x_row):
      err[i]=sigmoid_der[i]-one_hot_label_column[i]
    return err

  #define the training function

  def train(train_x,one_hot_label,theta,alpha,epoch):
    #error_cost=[]
    for i in range(clas):
      for j in range(epoch):
        pred=log_reg.hypothesis(train_x,theta[:,i])
        sigmoid_output=log_reg.sigmoid(pred)
        sigmoid_der=log_reg.sigmoid_grad(sigmoid_output)
        err=log_reg.error(sigmoid_output,one_hot_label[:,i])
        final_error=np.dot(train_x.T,np.multiply(sigmoid_der,err))
        theta[:,i]-=alpha*final_error
        
    return theta

In [ ]:
#initialize theta array with random numbers

np.random.seed(0)
theta=np.random.rand(train_x_col,clas).astype('float64')

In [ ]:
#call the training function to train the dataset
#passing 0.001 as learning rate & 500 as epoch

theta=log_reg.train(train_x,one_hot_label,theta,0.001,500)

In [ ]:
#print the theta values

print(theta)

[[0.54880904 0.71517801 0.60270837 ... 0.89175585 0.96363576 0.38344113]
 [0.79172504 0.52889492 0.56804456 ... 0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 ... 0.94466892 0.52184832 0.41466194]
 ...
 [0.33454415 0.90685483 0.07935625 ... 0.5302586  0.69834735 0.54570634]
 [0.9224717  0.55167759 0.91966573 ... 0.34255462 0.89937395 0.14921479]
 [0.49014489 0.10474855 0.15254681 ... 0.66072791 0.49932947 0.34177239]]


In [ ]:
#load the test dataset

data=pd.read_csv('sample_data/mnist_test.csv')

In [ ]:
#split 'data' into feature set 'test_X' and label 'test_y'

test_y,test_X=np.hsplit(data,[1])
print(test_y.head())
print(test_X.head())

   7
0  2
1  1
2  0
3  4
4  1
   0  0.1  0.2  0.3  0.4  0.5  ...  0.662  0.663  0.664  0.665  0.666  0.667
0  0    0    0    0    0    0  ...      0      0      0      0      0      0
1  0    0    0    0    0    0  ...      0      0      0      0      0      0
2  0    0    0    0    0    0  ...      0      0      0      0      0      0
3  0    0    0    0    0    0  ...      0      0      0      0      0      0
4  0    0    0    0    0    0  ...      0      0      0      0      0      0

[5 rows x 784 columns]


In [ ]:
#normalize the feature set 'test_X' to get 'test_x'

test_x=test_X.copy()
test_maximum=test_x.max().max()
print(test_maximum)

test_x=test_x.div(test_maximum)
test_x=test_x.astype('float64')
print (test_x.sample(5))

255
        0  0.1  0.2  0.3  0.4  0.5  ...  0.662  0.663  0.664  0.665  0.666  0.667
3232  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
8795  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
4990  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
9994  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
7442  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0

[5 rows x 784 columns]


In [ ]:
#Add the bias column to the feature dataframe 'test_x'

test_x=pd.concat([pd.Series(1.0,index=test_x.index,name='00'),test_x],axis=1)
print(test_x.head())

#'test_x_row' = number of rows in feature set 'test_x'
test_x_row=test_x.shape[0]
print(test_x_row)

#'test_x_col' = number of columns in feature set 'test_x'
test_x_col=test_x.shape[1]
print(test_x_col)

    00    0  0.1  0.2  0.3  0.4  ...  0.662  0.663  0.664  0.665  0.666  0.667
0  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
1  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
2  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
3  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0
4  1.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0

[5 rows x 785 columns]
9999
785


In [ ]:
#convert the dataframes into numpy arrays

test_y=test_y.to_numpy()
test_x=test_x.to_numpy()

In [ ]:
#create one_hot_label for test dataset

test_one_hot_label=np.empty([test_x_row,clas])
for i in range(clas):
    for j in range(test_x_row):
        if(test_y[j]==u[i]):
            test_one_hot_label[j,i]=1
        else:
            test_one_hot_label[j,i]=0
print(test_one_hot_label[:10]) 

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
#predict values in test dataset

test_output=np.empty([clas,test_x_row])
for i in range(clas):
  t_output=log_reg.hypothesis(test_x,theta)
  t_likelihood=log_reg.sigmoid(t_output)
  np.append(test_output,t_likelihood)
print(test_output)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [ ]:
#calculate accuracy for test dataset

test_accuracy = 0
for col in range(0, 10):
    for row in range(test_x_row):
        if test_one_hot_label[row][col] == 1 and test_output[col][row] >= 0.5:
            test_accuracy += 1
test_accuracy = test_accuracy/train_x_row
print(test_accuracy)

0.4999749987499375
